<?php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Check if language parameter is set via GET request
if (isset($_GET['lang'])) {
    $_SESSION['lang'] = $_GET['lang'];
}

// Default language is English
$current_lang = $_SESSION['lang'] ?? 'en';

// Translation Dictionaries
$translations = [
    'en' => [
        // Index / General Keys
        'title' => 'AGRICULTURE EQUIPMENT RENTAL SYSTEM',
        'hero_title' => 'Smart Solutions for Modern Farming',
        'hero_sub' => 'Rent quality agricultural equipment easily and grow your productivity.',
        'login' => 'Login',
        'register' => 'Register',
        'trusted' => 'Trusted & Secure',
        'trusted_desc' => 'Your data is safe with us',
        'quality' => 'Quality Equipment',
        'quality_desc' => 'Well-maintained and reliable',
        'near' => 'Near You',
        'near_desc' => 'Find equipment nearby',
        // Login & Navigation Keys
        'title'             => 'Agriculture Equipment Rental System',
        'home'              => 'Home',
        'how_it_works'      => 'How It Works',
        'welcome_back'      => 'Welcome Back!',
        'login_sub'         => 'Login to your account and start renting the best agricultural equipment near you.',
        'login'             => 'Login',
        'register'          => 'Register',
        'email_or_phone'    => 'Email / Phone Number',
        'enter_email_phone' => 'Enter your email or mobile number',
        'password'          => 'Password',
        'enter_password'    => 'Enter your password',
        'remember_me'       => 'Remember Me',
        'forgot_password'   => 'Forgot Password?',
        'dont_have_account' => "Don't have an account?",
        'register' => 'Register',
        'trusted' => 'Trusted & Secure',
        'trusted_desc' => 'Your information is safely stored with us',
        'quality' => 'Quality Equipment',
        'quality_desc' => 'Well-maintained and top-tier condition',
        'near' => 'Near You',
        'near_desc' => 'Find equipment in your local area',
        'terms_notice' => 'By logging in, you agree to our <a href="#" class="text-success text-decoration-none fw-semibold">Terms & Conditions</a> and <a href="#" class="text-success text-decoration-none fw-semibold">Privacy Policy</a>.',
        'popular_categories' => 'POPULAR CATEGORIES',
        'tractor' => 'Tractor',
        'harvesting' => 'Harvesting',
        'irrigation' => 'Irrigation',
        'tillage' => 'Tillage',
        'seeding' => 'Seeding',
        'spraying' => 'Spraying',
        'all_rights_reserved' => 'All rights reserved.',
        // How it works
        'how_it_works' => 'How It Works',
        'how_it_works_sub' => 'Simple steps to rent or list agricultural equipment in your local area.',
        'for_renters' => 'For Renters (Farmers)',
        'search_equipment' => 'Search Equipment',
        'search_equipment_desc' => 'Find tractors, harvesters, or tillage tools available near your location.',
        'book_and_pay' => 'Book & Pay',
        'book_and_pay_desc' => 'Select your required rental duration and confirm the booking request securely.',
        'start_farming' => 'Start Farming',
        'start_farming_desc' => 'Get the equipment delivered or pick it up directly from the owner to start work.',
        'for_lenders' => 'For Equipment Owners (Lenders)',
        'list_equipment' => 'List Equipment',
        'list_equipment_desc' => 'Post details, pricing, and images of your idle tractors or farming tools.',
        'accept_requests' => 'Accept Requests',
        'accept_requests_desc' => 'Review incoming rental requests from local farmers and accept them easily.',
        'earn_income' => 'Earn Income',
        'earn_income_desc' => 'Receive payment directly once the rental agreement period is completed.',
        'popular_categories' => 'POPULAR CATEGORIES',
        'tractor' => 'Tractor',
        'harvesting' => 'Harvesting',
        'irrigation' => 'Irrigation',
        'tillage' => 'Tillage',
        'seeding' => 'Seeding',
        'spraying' => 'Spraying',
        'all_rights_reserved' => 'All rights reserved.',
        // Renter_dashboard
        'title' => 'Agriculture Equipment Rental System',
        'renter_dashboard' => 'Renter Dashboard',
        'welcome_back' => 'Welcome back',
        'find_and_rent' => 'Find and rent the best agricultural equipment near you.',
        'active_bookings' => 'Active Bookings',
        'upcoming_bookings' => 'Upcoming Bookings',
        'completed_rentals' => 'Completed Rentals',
        'total_spent' => 'Total Spent',
        'popular_categories' => 'Popular Categories',
        'featured_equipment' => 'Featured Equipment',
        'recent_bookings' => 'Recent Bookings',
        'view_details' => 'View Details',
        'view_all' => 'View All',
        'search_placeholder' => 'Search equipment...',
        'no_active_rentals' => 'No active rentals yet',
        'no_categories' => 'No equipment categories available yet',
        'location' => 'Location',
        'logout' => 'Logout',
        'dashboard'          => 'Dashboard',
        'search_equipment'   => 'Search Equipment',
        'categories'         => 'Categories',
        'featured_equipment' => 'Featured Equipment',
        'recommended'        => 'Recommended',
        'my_bookings'        => 'My Bookings',
        'rental_history'     => 'Rental History',
        'my_profile'         => 'My Profile',
        'logout'             => 'Logout',
        'no_categories' => 'No equipment categories available yet',
        'browse_equipment' => 'Browse Equipment',
        // Categories
        'home'                  => 'Home',
       'equipment_categories'  => 'Equipment Categories',
        'categories_desc'       => 'Browse equipment by categories and find what you need.',
         'cant_find_title'       => "Can't find what you're looking for?",
            'try_searching'         => 'Try searching equipment',
       'equipment_count'       => 'Equipment',
         'view_equipment'        => 'View Equipment',
          'add_category'          => 'Add Category',
         'category_name'         => 'Category Name',
          'category_desc'         => 'Category Description',
         'category_image'        => 'Category Image',
           'category_icon'         => 'FontAwesome Icon Class',
           'save'                  => 'Save Category',
          'secure_platform'       => 'Secure & Trusted Platform',
          'secure_sub'            => '100% secure bookings • Verified owners • Safe payments (COD)',
          'verified_eq'           => 'Verified Equipment',
         'secure_booking'        => 'Secure Booking',
          'easy_cancel'           => 'Easy Cancellation',
            'support_247'           => '24/7 Support',
            // Forgot password
        'title' => 'Account Recovery',
        'enter_email' => 'Enter Registered Email:',
        'choose_method' => 'Choose Reset Method:',
        'method_otp' => 'Send OTP Code to Email',
        'method_question' => 'Answer Security Question',
        'continue' => 'Continue',
        'enter_otp' => 'Enter 6-Digit OTP Code:',
        'verify_code' => 'Verify Code',
        'security_question' => 'Security Question:',
        'your_answer' => 'Your Answer:',
        'verify_answer' => 'Verify Answer',
        'new_password' => 'New Password:',
        'confirm_password' => 'Confirm New Password:',
        'reset_btn' => 'Update Password & Login',
        'back_login' => 'Back to Login',
        'err_no_account' => 'No account found with that email address.',
        'err_no_question' => 'No security question set. Please use OTP recovery.',
        'err_invalid_otp' => 'Invalid or expired OTP code.',
        'err_wrong_answer' => 'Incorrect answer to security question.',
        'err_pwd_mismatch' => 'Passwords do not match.',
        'err_pwd_length' => 'Password must be at least 6 characters long.',
        'err_update_failed' => 'Failed to update password. Please try again.',
        // Lender dashboard
        'title'             => 'Agriculture Equipment Rental System',
          'lender_dashboard' => 'LENDER DASHBOARD',
        'dashboard' => 'Dashboard',
        'add_equipment' => 'Add Equipment',
        'my_equipment' => 'My Equipment',
        'rental_requests' => 'Rental Requests',
        'active_rentals' => 'Active Rentals',
        'rental_history' => 'Rental History',
        'total_earnings' => 'Total Earnings',
        'my_profile' => 'My Profile',
        'logout' => 'Logout',
        'search_placeholder' => 'Search anything...',
        
        // Banner & Stat Cards
        'welcome' => 'Welcome',
        'banner_subtitle' => 'Manage your equipment, rentals, and grow your business.',
        'total_equipment' => 'Total Equipment',
        'view_details' => 'View Details →',
        'view_all' => 'View All →',
        
        // Table Headers
        'renter' => 'Renter',
        'equipment' => 'Equipment',
        'from_to' => 'From - To',
        'amount' => 'Amount',
        'action' => 'Action',
        'accept' => 'Accept',
        'reject' => 'Reject',
        'in_use' => 'In Use',

        // Empty States
        'no_pending_requests' => 'No pending rental requests found.',
        'no_active_rentals' => 'No active equipment rentals.',

        //add_items page translations
          // Sidebar
        'dashboard' => 'Dashboard',
        'my_equipment' => 'My Equipment',
        'add_equipment' => 'Add Equipment',
        'rental_requests' => 'Rental Requests',
        'my_bookings' => 'My Bookings',
        'active_rentals' => 'Active Rentals',
        'total_earnings' => 'Total Earnings',
        'service_areas' => 'Service Areas',
        'reviews' => 'Reviews',
        'profile_settings' => 'Profile Settings',
        'logout' => 'Logout',
        'lender' => 'Lender',

        // Header & Page Titles
        'page_title' => 'Add New Equipment',
        'home' => 'Home',
        'back_dashboard' => 'Back to Dashboard',
        'header_badge' => 'ADD EQUIPMENT',
        'header_subtitle' => 'Fill in details to register machinery for rent',

        // Section 1: Equipment Details
        'sec_details' => '1. Equipment Details',
        'eq_name' => 'Equipment Name',
        'eq_name_ph' => 'Enter equipment name',
        'category' => 'Category',
        'select_category' => '-- Select Category --',
        'brand' => 'Brand',
        'brand_ph' => 'Enter brand name',
        'model' => 'Model',
        'model_ph' => 'Enter model',
        'year_purchase' => 'Year of Purchase',
        'condition' => 'Condition',
        'select_condition' => '-- Select Condition --',
        'description' => 'Description',
        'description_ph' => 'Enter equipment description, features and specifications...',

        // Section 2: Pricing & Availability
        'sec_pricing' => '2. Pricing & Availability',
        'price_per_day' => 'Price Per Day (₹)',
        'price_per_day_ph' => 'Enter price per day',
        'security_deposit' => 'Security Deposit (₹)',
        'security_deposit_ph' => 'Enter security deposit (optional)',
        'min_rental' => 'Min. Rental Days',
        'max_rental' => 'Max. Rental Days',
        'max_rental_ph' => 'Enter maximum days (optional)',
        'avail_status' => 'Available Status',
        'available' => 'Available',
        'not_available' => 'Not Available',

        // Section 3: Equipment Images
        'sec_images' => '3. Equipment Images',
        'drag_drop' => 'Drag & drop images here',
        'or' => 'or',
        'choose_files' => 'Choose Files',
        'image_specs' => 'JPG, PNG or WEBP (Max. 5MB)',

        // Section 4: Service Areas
        'sec_service_areas' => '4. Service Areas',
        'select_service_areas' => 'Select Service Areas',
        'add_custom_area' => '+ Add Custom Area',
        'prompt_custom_area' => 'Enter custom area name:',

        // Section 5: Additional Information
        'sec_additional' => '5. Additional Information',
        'fuel_type' => 'Fuel Type',
        'select_fuel' => '-- Select Fuel Type --',
        'power_hp' => 'Power (HP)',
        'power_hp_ph' => 'Enter power in HP',
        'working_hours' => 'Working Hours',
        'working_hours_ph' => 'Enter working hours',
        'mark_recommended' => 'Mark as Recommended Equipment',
        'recommended_desc' => 'This will show your equipment on homepage as recommended.',

        // Buttons
        'reset' => 'Reset',
        'save_equipment' => 'Save Equipment'
        

    ],




    'kn' => [
         // Index / General Keys
        'title' => 'ಕೃಷಿ ಉಪಕರಣ ಬಾಡಿಗೆ ವ್ಯವಸ್ಥೆ',
        'hero_title' => 'ಆಧುನಿಕ ಕೃಷಿಗಾಗಿ ಸ್ಮಾರ್ಟ್ ಪರಿಹಾರಗಳು',
        'hero_sub' => 'ಉತ್ತಮ ಗುಣಮಟ್ಟದ ಕೃಷಿ ಉಪಕರಣಗಳನ್ನು ಸುಲಭವಾಗಿ ಬಾಡಿಗೆಗೆ ಪಡೆಯಿರಿ.',
        'login' => 'ಲಾಗಿನ್',
        'register' => 'ನೋಂದಣಿ',
        'trusted' => 'ವಿಶ್ವಾಸಾರ್ಹ ಮತ್ತು ಸುರಕ್ಷಿತ',
        'trusted_desc' => 'ನಿಮ್ಮ ಡೇಟಾ ನಮ್ಮ ಬಳಿ ಸುರಕ್ಷಿತವಾಗಿದೆ',
        'quality' => 'ಗುಣಮಟ್ಟದ ಉಪಕರಣಗಳು',
        'quality_desc' => 'ಉತ್ತಮ ನಿರ್ವಹಣೆ ಮತ್ತು ನಂಬಿಕಸ್ಥ',
        'near' => 'ನಿಮ್ಮ ಹತ್ತಿರ',
        'near_desc' => 'ಸಮೀಪದ ಉಪಕರಣಗಳನ್ನು ಹುಡುಕಿ',
        // Login & Navigation Keys
        'home'              => 'ಮುಖ್ಯ ಪುಟ',
        'how_it_works'      => 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
        'welcome_back'      => 'ಮತ್ತೆ ಸ್ವಾಗತ!',
        'login_sub'         => 'ನಿಮ್ಮ ಖಾತೆಗೆ ಲಾಗಿನ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಹತ್ತಿರದ ಅತ್ಯುತ್ತಮ ಕೃಷಿ ಉಪಕರಣಗಳನ್ನು ಬಾಡಿಗೆಗೆ ಪಡೆಯಿರಿ.',
        'email_or_phone'    => 'ಇಮೇಲ್ / ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
        'enter_email_phone' => 'ನಿಮ್ಮ ಇಮೇಲ್ ಅಥವಾ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
        'password'          => 'ಪಾಸ್ವರ್ಡ್',
        'enter_password'    => 'ನಿಮ್ಮ ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ',
        'remember_me'       => 'ನನ್ನನ್ನು ನೆನಪಿಡಿ',
        'forgot_password'   => 'ಪಾಸ್ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?',
        'dont_have_account' => 'ಖಾತೆ ಇಲ್ಲವೇ?',
        'register' => 'ನೋಂದಣಿ',
        'trusted' => 'ವಿಶ್ವಾಸಾರ್ಹ ಮತ್ತು ಸುರಕ್ಷಿತ',
        'trusted_desc' => 'ನಿಮ್ಮ ವಿವರಗಳು ನಮ್ಮ ಬಳಿ ಸುರಕ್ಷಿತವಾಗಿವೆ',
        'quality' => 'ಗುಣಮಟ್ಟದ ಉಪಕರಣಗಳು',
        'quality_desc' => 'ಉತ್ತಮ ನಿರ್ವಹಣೆ ಮತ್ತು ಸುಸ್ಥಿತಿ',
        'near' => 'ನಿಮ್ಮ ಹತ್ತಿರ',
        'near_desc' => 'ಸಮೀಪದ ಉಪಕರಣಗಳನ್ನು ಹುಡುಕಿ',
        'terms_notice' => 'ಲಾಗಿನ್ ಮಾಡುವ ಮೂಲಕ, ನೀವು ನಮ್ಮ <a href="#" class="text-success text-decoration-none fw-semibold">ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು</a> ಮತ್ತು <a href="#" class="text-success text-decoration-none fw-semibold">ಗೌಪ್ಯತಾ ನೀತಿ</a>ಗೆ ಒಪ್ಪುತ್ತೀರಿ.',
        'popular_categories' => 'ಜನಪ್ರಿಯ ವರ್ಗಗಳು',
        'tractor' => 'ಟ್ರಾಕ್ಟರ್',
        'harvesting' => 'ಕೊಯ್ಲು',
        'irrigation' => 'ನೀರಾವರಿ',
        'tillage' => 'ಉಳುಮೆ',
        'seeding' => 'ಬಿತ್ತನೆ',
        'spraying' => 'ಸಿಂಪಡಣೆ',
        'all_rights_reserved' => 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
        // how it works
          'how_it_works' => 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
          'how_it_works_sub' => 'ನಿಮ್ಮ ಸ್ಥಳೀಯ ಪ್ರದೇಶದಲ್ಲಿ ಕೃಷಿ ಉಪಕರಣಗಳನ್ನು ಬಾಡಿಗೆಗೆ ಪಡೆಯಲು ಅಥವಾ ನೀಡಲು ಸರಳ ಹಂತಗಳು.',
          'for_renters' => 'ಬಾಡಿಗೆದಾರರಿಗೆ (ರೈತರಿಗೆ)',
          'search_equipment' => 'ಉಪಕರಣಗಳನ್ನು ಹುಡುಕಿ',
          'search_equipment_desc' => 'ನಿಮ್ಮ ಹತ್ತಿರ ಲಭ್ಯವಿರುವ ಟ್ರ್ಯಾಕ್ಟರ್‌ಗಳು, ಕೊಯ್ಲು ಯಂತ್ರಗಳು ಅಥವಾ ಉಳುವಿಕೆ ಉಪಕರಣಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಿ.',
          'book_and_pay' => 'ಬುಕ್ ಮಾಡಿ ಮತ್ತು ಪಾವತಿಸಿ',
          'book_and_pay_desc' => 'ನಿಮಗೆ ಅಗತ್ಯವಿರುವ ಬಾಡಿಗೆಯ ಸಮಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ ಮತ್ತು ಬುಕಿಂಗ್ ಅನ್ನು ದೃಢೀಕರಿಸಿ.',
          'start_farming' => 'ಬೆಳೆ ಕೃಷಿ ಪ್ರಾರಂಭಿಸಿ',
          'start_farming_desc' => 'ಉಪಕರಣಗಳನ್ನು ಮನೆಗೆ ತರಿಸಿಕೊಳ್ಳಿ ಅಥವಾ ಮಾಲೀಕರಿಂದ ನೇರವಾಗಿ ಪಡೆದುಕೊಂಡು ಕೆಲಸ ಪ್ರಾರಂಭಿಸಿ.',
          'for_lenders' => 'ಉಪಕರಣಗಳ ಮಾಲೀಕರಿಗೆ (ನೀಡುವವರಿಗೆ)',
          'list_equipment' => 'ಉಪಕರಣಗಳ ಮಾಹಿತಿ ನೀಡಿ',
          'list_equipment_desc' => 'ನಿಮ್ಮ ಬಳಿ ಸುಮ್ಮನೆ ಇರುವ ಟ್ರ್ಯಾಕ್ಟರ್ ಅಥವಾ ಕೃಷಿ ಉಪಕರಣಗಳ ವಿವರ, ದರ ಮತ್ತು ಚಿತ್ರಗಳನ್ನು ಸೇರಿಸಿ.',
          'accept_requests' => 'ಕೋರಿಕೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ',
          'accept_requests_desc' => 'ಸ್ಥಳೀಯ ರೈತರಿಂದ ಬರುವ ಬಾಡಿಗೆ ಕೋರಿಕೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸುಲಭವಾಗಿ ಸ್ವೀಕರಿಸಿ.',
          'earn_income' => 'ಆದಾಯ ಗಳಿಸಿ',
          'earn_income_desc' => 'ಬಾಡಿಗೆಯ ಸಮಯ ಮುಗಿದ ನಂತರ ನೇರವಾಗಿ ಹಣವನ್ನು ಪಡೆದುಕೊಳ್ಳಿ.',
           'popular_categories' => 'ಜನಪ್ರಿಯ ವರ್ಗಗಳು',
        'tractor' => 'ಟ್ರಾಕ್ಟರ್',
        'harvesting' => 'ಕೊಯ್ಲು',
        'irrigation' => 'ನೀರಾವರಿ',
        'tillage' => 'ಉಳುಮೆ',
        'seeding' => 'ಬಿತ್ತನೆ',
        'spraying' => 'ಸಿಂಪಡಣೆ',
        'all_rights_reserved' => 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
            // renter_dashboard
        'title' => 'ಕೃಷಿ ಉಪಕರಣ ಬಾಡಿಗೆ ವ್ಯವಸ್ಥೆ',
        'renter_dashboard' => 'ಬಾಡಿಗೆದಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        'welcome_back' => 'ಸ್ವಾಗತ',
        'find_and_rent' => 'ನಿಮ್ಮ ಹತ್ತಿರವಿರುವ ಉತ್ತಮ ಕೃಷಿ ಉಪಕರಣಗಳನ್ನು ಹುಡುಕಿ ಮತ್ತು ಬಾಡಿಗೆಗೆ ಪಡೆಯಿರಿ.',
        'active_bookings' => 'ಸಕ್ರಿಯ ಬುಕಿಂಗ್‌ಗಳು',
        'upcoming_bookings' => 'ಮುಂಬರುವ ಬುಕಿಂಗ್‌ಗಳು',
        'completed_rentals' => 'ಪೂರ್ಣಗೊಂಡ ಬಾಡಿಗೆಗಳು',
        'total_spent' => 'ಒಟ್ಟು ವೆಚ್ಚ',
        'popular_categories' => 'ಜನಪ್ರಿಯ ವರ್ಗಗಳು',
        'featured_equipment' => 'ವಿಶೇಷ ಉಪಕರಣಗಳು',
        'recent_bookings' => 'ಇತ್ತೀಚಿನ ಬುಕಿಂಗ್‌ಗಳು',
        'view_details' => 'ವಿವರ ವೀಕ್ಷಿಸಿ',
        'view_all' => 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
        'search_placeholder' => 'ಉಪಕರಣಗಳನ್ನು ಹುಡುಕಿ...',
        'no_active_rentals' => 'ಇನ್ನೂ ಯಾವುದೇ ಸಕ್ರಿಯ ಬಾಡಿಗೆಗಳಿಲ್ಲ',
        'no_categories' => 'ಯಾವುದೇ ಉಪಕರಣಗಳ ವರ್ಗಗಳು ಲಭ್ಯವಿಲ್ಲ',
        'location' => 'ಸ್ಥಳ',
        'logout' => 'ನಿರ್ಗಮಿಸಿ',
        'dashboard'          => 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        'search_equipment'   => 'ಉಪಕರಣಗಳನ್ನು ಹುಡುಕಿ',
        'categories'         => 'ವರ್ಗಗಳು',
        'featured_equipment' => 'ವಿಶೇಷ ಉಪಕರಣಗಳು',
         'recommended'        => 'ಶಿಫಾರಸು ಮಾಡಿದವು',
        'my_bookings'        => 'ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು',
        'rental_history'     => 'ಬಾಡಿಗೆ ಇತಿಹಾಸ',
        'my_profile'         => 'ನನ್ನ ಪ್ರೊಫೈಲ್',
        'logout'             => 'ಲಾಗಿನ್‌ನಿಂದ ನಿರ್ಗಮಿಸಿ',
        'no_categories' => 'ಯಾವುದೇ ಉಪಕರಣಗಳ ವರ್ಗಗಳು ಲಭ್ಯವಿಲ್ಲ',
        'browse_equipment' => 'ಉಪಕರಣಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
        // Categories
        'home'                  => 'ಮುಖಪುಟ',
        'equipment_categories'  => 'ಉಪಕರಣ ವರ್ಗಗಳು',
        'categories_desc'       => 'ವರ್ಗಗಳ ಮೂಲಕ ಉಪಕರಣಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ ಮತ್ತು ನೀವು ಬೇಕಾದುದನ್ನು ಕಂಡುಕೊಳ್ಳಿ.',
        'try_searching'         => 'ಉಪಕರಣಗಳನ್ನು ಹುಡುಕಲು ಪ್ರಯತ್ನಿಸಿ',
        'equipment_count'       => 'ಉಪಕರಣಗಳು',
         'view_equipment'        => 'ಉಪಕರಣ ವೀಕ್ಷಿಸಿ',
        'add_category'          => 'ವರ್ಗವನ್ನು ಸೇರಿಸಿ',
        'category_name'         => 'ವರ್ಗದ ಹೆಸರು',
          'category_desc'         => 'ವರ್ಗದ ವಿವರಣೆ',
         'category_image'        => 'ವರ್ಗದ ಚಿತ್ರ',
        'category_icon'         => 'ಐಕಾನ್ ತರಗತಿ',
        'save'                  => 'ವರ್ಗ ಉಳಿಸಿ',
          'secure_platform'       => 'ಸುರಕ್ಷಿತ ಮತ್ತು ವಿಶ್ವಾಸಾರ್ಹ ತಾಣ',
         'secure_sub'            => '100% ಸುರಕ್ಷಿತ ಬುಕಿಂಗ್ • ದೃಢೀಕರಿಸಲ್ಪಟ್ಟ ಮಾಲೀಕರು • ಸುರಕ್ಷಿತ ಪಾವತಿಗಳು',
        'verified_eq'           => 'ದೃಢೀಕೃತ ಉಪಕರಣಗಳು',
          'secure_booking'        => 'ಸುರಕ್ಷಿತ ಬುಕಿಂಗ್',
         'easy_cancel'           => 'ಸುಲಭ ರದ್ದತಿ',
         'support_247'           => '24/7 ಬೆಂಬಲ',
         // forgot password
         'title' => 'ಖಾತೆ ಮರುಪಡೆಯುವಿಕೆ',
        'enter_email' => 'ನೋಂದಾಯಿತ ಇಮೇಲ್ ನಮೂದಿಸಿ:',
        'choose_method' => 'ಮರುಹೊಂದಿಸುವ ವಿಧಾನವನ್ನು ಆಯ್ಕೆಮಾಡಿ:',
        'method_otp' => 'ಇಮೇಲ್‌ಗೆ OTP ಕಳುಹಿಸಿ',
        'method_question' => 'ಸುರಕ್ಷತಾ ಪ್ರಶ್ನೆಗೆ ಉತ್ತರಿಸಿ',
        'continue' => 'ಮುಂದುವರೆಯಿರಿ',
        'enter_otp' => '6-ಅಂಕಿಯ OTP ಕೋಡ್ ನಮೂದಿಸಿ:',
        'verify_code' => 'ಕೋಡ್ ಪರಿಶೀಲಿಸಿ',
        'security_question' => 'ಸುರಕ್ಷತಾ ಪ್ರಶ್ನೆ:',
        'your_answer' => 'ನಿಮ್ಮ ಉತ್ತರ:',
        'verify_answer' => 'ಉತ್ತರವನ್ನು ಪರಿಶೀಲಿಸಿ',
        'new_password' => 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್:',
        'confirm_password' => 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ಖಚಿತಪಡಿಸಿ:',
        'reset_btn' => 'ಪಾಸ್‌ವರ್ಡ್ ನವೀಕರಿಸಿ ಮತ್ತು ಲಾಗಿನ್ ಮಾಡಿ',
        'back_login' => 'ಲಾಗಿನ್‌ಗೆ ಹಿಂತಿರುಗಿ',
        'err_no_account' => 'ಆ ಇಮೇಲ್ ವಿಳಾಸದೊಂದಿಗೆ ಯಾವುದೇ ಖಾತೆ ಕಂಡುಬಂದಿಲ್ಲ.',
        'err_no_question' => 'ಸುರಕ್ಷತಾ ಪ್ರಶ್ನೆ ಹೊಂದಿಸಿಲ್ಲ. ದಯವಿಟ್ಟು OTP ಬಳಸಿ.',
        'err_invalid_otp' => 'ಅಮಾನ್ಯ ಅಥವಾ ಅವಧಿ ಮುಗಿದ OTP ಕೋಡ್.',
        'err_wrong_answer' => 'ಸುರಕ್ಷತಾ ಪ್ರಶ್ನೆಗೆ ತಪ್ಪು ಉತ್ತರ.',
        'err_pwd_mismatch' => 'ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ.',
        'err_pwd_length' => 'ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳನ್ನು ಹೊಂದಿರಬೇಕು.',
        'err_update_failed' => 'ಪಾಸ್‌ವರ್ಡ್ ನವೀಕರಿಸಲು ವಿಫಲವಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
        // lender dashboard
           'title' => 'ಕೃಷಿ ಉಪಕರಣ ಬಾಡಿಗೆ ವ್ಯವಸ್ಥೆ',
          'lender_dashboard' => 'ಉಪಕರಣ ಮಾಲೀಕರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        'dashboard' => 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        'add_equipment' => 'ಉಪಕರಣ ಸೇರಿಸಿ',
        'my_equipment' => 'ನನ್ನ ಉಪಕರಣಗಳು',
        'rental_requests' => 'ಬಾಡಿಗೆ ವಿನಂತಿಗಳು',
        'active_rentals' => 'ಸಕ್ರಿಯ ಬಾಡಿಗೆಗಳು',
        'rental_history' => 'ಬಾಡಿಗೆ ಇತಿಹಾಸ',
        'total_earnings' => 'ಒಟ್ಟು ಗಳಿಕೆ',
        'my_profile' => 'ನನ್ನ ಪ್ರೊಫೈಲ್',
        'logout' => 'ಲಾಗ್‌ಔಟ್',
        'search_placeholder' => 'ಹುಡುಕಿ...',
        
        'welcome' => 'ಸ್ವಾಗತ',
        'banner_subtitle' => 'ನಿಮ್ಮ ಉಪಕರಣಗಳು, ಬಾಡಿಗೆಗಳು ಮತ್ತು ವ್ಯವಹಾರವನ್ನು ನಿರ್ವಹಿಸಿ.',
        'total_equipment' => 'ಒಟ್ಟು ಉಪಕರಣಗಳು',
        'view_details' => 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ →',
        'view_all' => 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ →',
        
        'renter' => 'ಬಾಡಿಗೆದಾರ',
        'equipment' => 'ಉಪಕರಣ',
        'from_to' => 'ದಿನಾಂಕದಿಂದ - ದಿನಾಂಕದವರೆಗೆ',
        'amount' => 'ಮೊತ್ತ',
        'action' => 'ಕ್ರಿಯೆ',
        'accept' => 'ಸಮ್ಮತಿಸಿ',
        'reject' => 'ನಿರಾಕರಿಸಿ',
        'in_use' => 'ಬಳಕೆಯಲ್ಲಿದೆ',

        'no_pending_requests' => 'ಯಾವುದೇ ಬಾಕಿ ಇರುವ ಬಾಡಿಗೆ ವಿನಂತಿಗಳಿಲ್ಲ.',
        'no_active_rentals' => 'ಯಾವುದೇ ಸಕ್ರಿಯ ಉಪಕರಣ ಬಾಡಿಗೆಗಳಿಲ್ಲ.',
        'Reviews' => 'ವಿಮರ್ಶೆಗಳು',

        // add.items page transaltions
        // Sidebar
        'dashboard' => 'ಮುಖಪುಟ (Dashboard)',
        'my_equipment' => 'ನನ್ನ ಉಪಕರಣಗಳು',
        'add_equipment' => 'ಉಪಕರಣವನ್ನು ಸೇರಿಸಿ',
        'rental_requests' => 'ಬಾಡಿಗೆ ವಿನಂತಿಗಳು',
        'my_bookings' => 'ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು',
        'active_rentals' => 'ಸಕ್ರಿಯ ಬಾಡಿಗೆಗಳು',
        'total_earnings' => 'ಒಟ್ಟು ಗಳಿಕೆ',
        'service_areas' => 'ಸೇವಾ ಪ್ರದೇಶಗಳು',
        'reviews' => 'ವಿಮರ್ಶೆಗಳು',
        'profile_settings' => 'ಪ್ರೊಫೈಲ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
        'logout' => 'ಹೊರನಡೆ',
        'lender' => 'ಉಪಕರಣ ಮಾಲೀಕ',

        // Header & Page Titles
        'page_title' => 'ಹೊಸ ಉಪಕರಣವನ್ನು ಸೇರಿಸಿ',
        'home' => 'ಮುಖಪುಟ',
        'back_dashboard' => 'ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',
        'header_badge' => 'ಉಪಕರಣ ಸೇರಿಸಿ',
        'header_subtitle' => 'ಬಾಡಿಗೆಗೆ ಯಂತ್ರೋಪಕರಣಗಳನ್ನು ನೋಂದಾಯಿಸಲು ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ',

        // Section 1: Equipment Details
        'sec_details' => '1. ಉಪಕರಣದ ವಿವರಗಳು',
        'eq_name' => 'ಉಪಕರಣದ ಹೆಸರು',
        'eq_name_ph' => 'ಉಪಕರಣದ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
        'category' => 'ವರ್ಗ',
        'select_category' => '-- ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ --',
        'brand' => 'ಬ್ರ್ಯಾಂಡ್',
        'brand_ph' => 'ಬ್ರ್ಯಾಂಡ್ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
        'model' => 'ಮಾದರಿ',
        'model_ph' => 'ಮಾದರಿಯನ್ನು ನಮೂದಿಸಿ',
        'year_purchase' => 'ಖরিদಿಸಿದ ವರ್ಷ',
        'condition' => 'ಸ್ಥಿತಿ',
        'select_condition' => '-- ಸ್ಥಿತಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ --',
        'description' => 'ವಿವರಣೆ',
        'description_ph' => 'ಉಪಕರಣದ ವಿವರಣೆ, ವೈಶಿಷ್ಟ್ಯಗಳು ಮತ್ತು ವಿಶೇಷತೆಗಳನ್ನು ನಮೂದಿಸಿ...',

        // Section 2: Pricing & Availability
        'sec_pricing' => '2. ಬೆಲೆ ಮತ್ತು ಲಭ್ಯತೆ',
        'price_per_day' => 'ದಿನದ ಬೆಲೆ (₹)',
        'price_per_day_ph' => 'ಪ್ರತಿ ದಿನದ ಬೆಲೆಯನ್ನು ನಮೂದಿಸಿ',
        'security_deposit' => 'ಭದ್ರತಾ ಠೇವಣಿ (₹)',
        'security_deposit_ph' => 'ಭದ್ರತಾ ಠೇವಣಿ ನಮೂದಿಸಿ (ಐಚ್ಛಿಕ)',
        'min_rental' => 'ಕನಿಷ್ಠ ಬಾಡಿಗೆ ದಿನಗಳು',
        'max_rental' => 'ಗರಿಷ್ಠ ಬಾಡಿಗೆ ದಿನಗಳು',
        'max_rental_ph' => 'ಗರಿಷ್ಠ ದಿನಗಳನ್ನು ನಮೂದಿಸಿ (ಐಚ್ಛಿಕ)',
        'avail_status' => 'ಲಭ್ಯತೆಯ ಸ್ಥಿತಿ',
        'available' => 'ಲಭ್ಯವಿದೆ',
        'not_available' => 'ಲಭ್ಯವಿಲ್ಲ',

        // Section 3: Equipment Images
        'sec_images' => '3. ಉಪಕರಣದ ಚಿತ್ರಗಳು',
        'drag_drop' => 'ಚಿತ್ರಗಳನ್ನು ಇಲ್ಲಿ ಎಳೆದು ಹಾಕಿ',
        'or' => 'ಅಥವಾ',
        'choose_files' => 'ಫೈಲ್‌ಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ',
        'image_specs' => 'JPG, PNG ಅಥವಾ WEBP (ಗರಿಷ್ಠ 5MB)',

        // Section 4: Service Areas
        'sec_service_areas' => '4. ಸೇವಾ ಪ್ರದೇಶಗಳು',
        'select_service_areas' => 'ಸೇವಾ ಪ್ರದೇಶಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ',
        'add_custom_area' => '+ ಕಸ್ಟಮ್ ಪ್ರದೇಶವನ್ನು ಸೇರಿಸಿ',
        'prompt_custom_area' => 'ಕಸ್ಟಮ್ ಪ್ರದೇಶದ ಹೆಸರನ್ನು ನಮೂದಿಸಿ:',

        // Section 5: Additional Information
        'sec_additional' => '5. ಹೆಚ್ಚುವರಿ ಮಾಹಿತಿ',
        'fuel_type' => 'ಇಂಧನ ಪ್ರಕಾರ',
        'select_fuel' => '-- ಇಂಧನ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ --',
        'power_hp' => 'ಶಕ್ತಿ (HP)',
        'power_hp_ph' => 'HP ನಲ್ಲಿ ಶಕ್ತಿಯನ್ನು ನಮೂದಿಸಿ',
        'working_hours' => 'ಕೆಲಸದ ಗಂಟೆಗಳು',
        'working_hours_ph' => 'ಕೆಲಸದ ಗಂಟೆಗಳನ್ನು ನಮೂದಿಸಿ',
        'mark_recommended' => 'ಶಿಫಾರಸು ಮಾಡಿದ ಉಪಕರಣವಾಗಿ ಗುರುತಿಸಿ',
        'recommended_desc' => 'ಇದು ನಿಮ್ಮ ಉಪಕರಣವನ್ನು ಮುಖಪುಟದಲ್ಲಿ ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ ಎಂದು ತೋರಿಸುತ್ತದೆ.',

        // Buttons
        'reset' => 'ಮರುಹೊಂದಿಸಿ',
        'save_equipment' => 'ಉಪಕರಣವನ್ನು ಉಳಿಸಿ'

        
    ],
    'hi' => [
        // Index / General Keys
        'title' => 'कृषि उपकरण किराया प्रणाली',
        'hero_title' => 'आधुनिक खेती के लिए स्मार्ट समाधान',
        'hero_sub' => 'गुणवत्तापूर्ण कृषि उपकरण आसानी से किराए पर लें।',
        'login' => 'लॉग इन',
        'register' => 'पंजीकरण',
        'trusted' => 'विश्वसनीय और सुरक्षित',
        'trusted_desc' => 'आपका डेटा हमारे पास सुरक्षित है',
        'quality' => 'गुणवत्ता उपकरण',
        'quality_desc' => 'अच्छी तरह से रखरखाव और विश्वसनीय',
        'near' => 'आपके पास',
        'near_desc' => 'आस-पास के उपकरण खोजें',
        // Login & Navigation Keys
        'home'              => 'होम',
        'how_it_works'      => 'यह कैसे काम करता है',
        'welcome_back'      => 'वेलकम बैक!',
        'login_sub'         => 'अपने खाते में लॉगिन करें और अपने पास के सबसे अच्छे कृषि उपकरणों को किराए पर लें।',
        'email_or_phone'    => 'ईमेल / फ़ोन नंबर',
        'enter_email_phone' => 'अपना ईमेल या मोबाइल नंबर दर्ज करें',
        'password'          => 'पासवर्ड',
        'enter_password'    => 'अपना पासवर्ड दर्ज करें',
        'remember_me'       => 'मुझे याद रखो',
        'forgot_password'   => 'पासवर्ड भूल गए?',
        'dont_have_account' => 'खाता नहीं है?',
        'register' => 'पंजीकरण',
        'trusted' => 'विश्वसनीय और सुरक्षित',
        'trusted_desc' => 'आपकी जानकारी हमारे पास सुरक्षित रूप से संग्रहीत है',
        'quality' => 'गुणवत्ता उपकरण',
        'quality_desc' => 'अच्छी तरह से रखरखाव और शीर्ष-स्तरीय स्थिति',
        'near' => 'आपके पास',
        'near_desc' => 'अपने स्थानीय क्षेत्र में उपकरण खोजें',
        'terms_notice' => 'लॉगिन करके, आप हमारी <a href="#" class="text-success text-decoration-none fw-semibold">नियम और शर्तें</a> और <a href="#" class="text-success text-decoration-none fw-semibold">गोपनीयता नीति</a> से सहमत होते हैं।',
        'popular_categories' => 'लोकप्रिय श्रेणियाँ',
        'tractor' => 'ट्रैक्टर',
        'harvesting' => 'फसल काटना',
        'irrigation' => 'सिंचाई',
        'tillage' => 'जुताई',
        'seeding' => 'बुवाई',
        'spraying' => 'छिड़काव',
        'all_rights_reserved' => 'सर्वाधिकार सुरक्षित।',
        // how it works
        'how_it_works' => 'यह कैसे काम करता है',
        'how_it_works_sub' => 'अपने स्थानीय क्षेत्र में कृषि उपकरण किराए पर लेने या देने के आसान चरण।',
        'for_renters' => 'किराएदारों के लिए (किसान)',
        'search_equipment' => 'उपकरण खोजें',
        'search_equipment_desc' => 'अपने पास उपलब्ध ट्रैक्टर, हार्वेस्टर या जुताई के उपकरण खोजें।',
        'book_and_pay' => 'बुक करें और भुगतान करें',
        'book_and_pay_desc' => 'अपनी आवश्यकता अनुसार समय चुनें और सुरक्षित रूप से बुकिंग की पुष्टि करें।',
        'start_farming' => 'खेती शुरू करें',
        'start_farming_desc' => 'उपकरण की डिलीवरी पाएं या सीधे मालिक से प्राप्त करके काम शुरू करें।',
        'for_lenders' => 'उपकरण मालिकों के लिए (किराए पर देने वाले)',
       'list_equipment' => 'उपकरण जोड़ें',
       'list_equipment_desc' => 'अपने खाली पड़े ट्रैक्टर या कृषि उपकरणों का विवरण, किराया और तस्वीरें अपलोड करें।',
       'accept_requests' => 'अनुरोध स्वीकार करें',
       'accept_requests_desc' => 'स्थानीय किसानों से मिलने वाले किराए के अनुरोधों की समीक्षा करें और स्वीकार करें।',
       'earn_income' => 'कमाई करें',
       'earn_income_desc' => 'किराए की अवधि पूरी होने पर सीधे भुगतान प्राप्त करें।',
        'popular_categories' => 'लोकप्रिय श्रेणियाँ',
        'tractor' => 'ट्रैक्टर',
        'harvesting' => 'फसल काटना',
        'irrigation' => 'सिंचाई',
        'tillage' => 'जुताई',
        'seeding' => 'बुवाई',
        'spraying' => 'छिड़काव',
        'all_rights_reserved' => 'सर्वाधिकार सुरक्षित।',
        // renter_dashboard
        'title' => 'कृषि उपकरण किराया प्रणाली',
        'renter_dashboard' => 'किराएदार डैशबोर्ड',
        'welcome_back' => 'वापसी पर आपका स्वागत है',
        'find_and_rent' => 'अपने आस-पास सर्वोत्तम कृषि उपकरण खोजें और किराए पर लें।',
        'active_bookings' => 'सक्रिय बुकिंग',
        'upcoming_bookings' => 'आगामी बुकिंग',
        'completed_rentals' => 'पूर्ण किराए',
        'total_spent' => 'कुल खर्च',
        'popular_categories' => 'लोकप्रिय श्रेणियां',
        'featured_equipment' => 'प्रमुख उपकरण',
        'recent_bookings' => 'हाल की बुकिंग',
        'view_details' => 'विवरण देखें',
        'view_all' => 'सभी देखें',
        'search_placeholder' => 'उपकरण खोजें...',
        'no_active_rentals' => 'अभी कोई सक्रिय बुकिंग नहीं है',
        'no_categories' => 'कोई उपकरण श्रेणी उपलब्ध नहीं है',
        'location' => 'स्थान',
        'logout' => 'लॉग आउट',
         'dashboard'          => 'डैशबोर्ड',
        'search_equipment'   => 'उपकरण खोजें',
        'categories'         => 'श्रेणियां',
        'featured_equipment' => 'प्रमुख उपकरण',
        'recommended'        => 'अनुशंसित',
        'my_bookings'        => 'मेरी बुकिंग',
        'rental_history'     => 'किराया इतिहास',
        'my_profile'         => 'मेरी प्रोफाइल',
        'logout'            => 'लॉग आउट',
        'no_categories' => 'कोई उपकरण श्रेणी उपलब्ध नहीं है',
        'browse_equipment' => 'उपकरण ब्राउज़ करें',
        // Categories
        'home'                  => 'होम',
'equipment_categories'  => 'उपकरण श्रेणियां',
'categories_desc'       => 'श्रेणियों के अनुसार उपकरण ब्राउज़ करें और अपनी आवश्यकता पाएं।',
'cant_find_title'       => 'क्या आपको वह नहीं मिल रहा जो आप ढूंढ रहे हैं?',
'try_searching'         => 'उपकरण खोजने का प्रयास करें',
'equipment_count'       => 'उपकरण',
'view_equipment'        => 'उपकरण देखें',
'add_category'          => 'श्रेणी जोड़ें',
'category_name'         => 'श्रेणी का नाम',
'category_desc'         => 'श्रेणी का विवरण',
'category_image'        => 'श्रेणी की छवि',
'category_icon'         => 'आइकन क्लास',
'save'                  => 'श्रेणी सहेजें',
'secure_platform'       => 'सुरक्षित और विश्वसनीय प्लेटफॉर्म',
'secure_sub'            => '100% सुरक्षित बुकिंग • सत्यापित मालिक • सुरक्षित भुगतान',
'verified_eq'           => 'सत्यापित उपकरण',
'secure_booking'        => 'सुरक्षित बुकिंग',
'easy_cancel'           => 'आसान रद्दीकरण',
'support_247'           => '24/7 सहायता',
// forgot password
   'title' => 'खाता रिकवरी',
        'enter_email' => 'पंजीकृत ईमेल दर्ज करें:',
        'choose_method' => 'रीसेट तरीका चुनें:',
        'method_otp' => 'ईमेल पर OTP भेजें',
        'method_question' => 'सुरक्षा प्रश्न का उत्तर दें',
        'continue' => 'आगे बढ़ें',
        'enter_otp' => '6-अंकों का OTP कोड दर्ज करें:',
        'verify_code' => 'कोड सत्यापित करें',
        'security_question' => 'सुरक्षा प्रश्न:',
        'your_answer' => 'आपका उत्तर:',
        'verify_answer' => 'उत्तर सत्यापित करें',
        'new_password' => 'नया पासवर्ड:',
        'confirm_password' => 'नए पासवर्ड की पुष्टि करें:',
        'reset_btn' => 'पासवर्ड अपडेट करें और लॉगिन करें',
        'back_login' => 'लॉगिन पर वापस जाएं',
        'err_no_account' => 'उस ईमेल पते के साथ कोई खाता नहीं मिला।',
        'err_no_question' => 'कोई सुरक्षा प्रश्न सेट नहीं है। कृपया OTP का उपयोग करें।',
        'err_invalid_otp' => 'अमान्य या समाप्त हो चुका OTP कोड।',
        'err_wrong_answer' => 'सुरक्षा प्रश्न का उत्तर गलत है।',
        'err_pwd_mismatch' => 'पासवर्ड मेल नहीं खाते।',
        'err_pwd_length' => 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।',
        'err_update_failed' => 'पासवर्ड अपडेट करने में विफल। कृपया पुनः प्रयास करें।',
         'dashboard' => 'डैशबोर्ड',
        'add_equipment' => 'उपकरण जोड़ें',
        'my_equipment' => 'मेरे उपकरण',
        'rental_requests' => 'किराए के अनुरोध',
        'active_rentals' => 'सक्रिय किराए',
        'total_equipment' => 'कुल उपकरण',
        'total_earnings' => 'कुल कमाई',
        'logout' => 'लॉगआउट',
        'welcome' => 'वापसी पर स्वागत है',
        // lender dashboard
          'title' => 'कृषि उपकरण किराया प्रणाली',
         'lender_dashboard' => 'लेंडर डैशबोर्ड',
        'dashboard' => 'डैशबोर्ड',
        'add_equipment' => 'उपकरण जोड़ें',
        'my_equipment' => 'मेरे उपकरण',
        'rental_requests' => 'किराए के अनुरोध',
        'active_rentals' => 'सक्रिय किराए',
        'rental_history' => 'किराया इतिहास',
        'total_earnings' => 'कुल कमाई',
        'my_profile' => 'मेरी प्रोफाइल',
        'logout' => 'लॉगआउट',
        'search_placeholder' => 'कुछ भी खोजें...',
        
        'welcome' => 'स्वागत है',
        'banner_subtitle' => 'अपने उपकरणों, किराए और व्यवसाय को प्रबंधित करें।',
        'total_equipment' => 'कुल उपकरण',
        'view_details' => 'विवरण देखें →',
        'view_all' => 'सभी देखें →',
        
        'renter' => 'किराएदार',
        'equipment' => 'उपकरण',
        'from_to' => 'कब से - कब तक',
        'amount' => 'राशि',
        'action' => 'कार्रवाई',
        'accept' => 'स्वीकार करें',
        'reject' => 'अस्वीकार करें',
        'in_use' => 'उपयोग में',

        'no_pending_requests' => 'कोई लंबित अनुरोध नहीं मिला।',
        'no_active_rentals' => 'कोई सक्रिय उपकरण किराया नहीं है।',
        'Reviews' => 'समीक्षाएँ',
          // add_items transaalations'
          // Sidebar
        'dashboard' => 'डैशबोर्ड',
        'my_equipment' => 'मेरे उपकरण',
        'add_equipment' => 'उपकरण जोड़ें',
        'rental_requests' => 'किराये के अनुरोध',
        'my_bookings' => 'मेरी बुकिंग',
        'active_rentals' => 'सक्रिय किराये',
        'total_earnings' => 'कुल कमाई',
        'service_areas' => 'सेवा क्षेत्र',
        'reviews' => 'समीक्षाएँ',
        'profile_settings' => 'प्रोफ़ाइल सेटिंग्स',
        'logout' => 'लॉग आउट',
        'lender' => 'ऋणदाता',

        // Header & Page Titles
        'page_title' => 'नया उपकरण जोड़ें',
        'home' => 'होम',
        'back_dashboard' => 'डैशबोर्ड पर वापस जाएं',
        'header_badge' => 'उपकरण जोड़ें',
        'header_subtitle' => 'किराए पर मशीनरी रजिस्टर करने के लिए विवरण भरें',

        // Section 1: Equipment Details
        'sec_details' => '1. उपकरण विवरण',
        'eq_name' => 'उपकरण का नाम',
        'eq_name_ph' => 'उपकरण का नाम दर्ज करें',
        'category' => 'श्रेणी',
        'select_category' => '-- श्रेणी चुनें --',
        'brand' => 'ब्रांड',
        'brand_ph' => 'ब्रांड का नाम दर्ज करें',
        'model' => 'मॉडल',
        'model_ph' => 'मॉडल दर्ज करें',
        'year_purchase' => 'खरीद का वर्ष',
        'condition' => 'स्थिति',
        'select_condition' => '-- स्थिति चुनें --',
        'description' => 'विवरण',
        'description_ph' => 'उपकरण का विवरण, विशेषताएँ और विनिर्देश दर्ज करें...',

        // Section 2: Pricing & Availability
        'sec_pricing' => '2. मूल्य निर्धारण और उपलब्धता',
        'price_per_day' => 'प्रति दिन मूल्य (₹)',
        'price_per_day_ph' => 'प्रति दिन मूल्य दर्ज करें',
        'security_deposit' => 'सुरक्षा जमा (₹)',
        'security_deposit_ph' => 'सुरक्षा जमा दर्ज करें (वैकल्पिक)',
        'min_rental' => 'न्यूनतम किराये के दिन',
        'max_rental' => 'अधिकतम किराये के दिन',
        'max_rental_ph' => 'अधिकतम दिन दर्ज करें (वैकल्पिक)',
        'avail_status' => 'उपलब्धता की स्थिति',
        'available' => 'उपलब्ध',
        'not_available' => 'उपलब्ध नहीं',

        // Section 3: Equipment Images
        'sec_images' => '3. उपकरण छवियां',
        'drag_drop' => 'यहाँ छवियाँ खींच कर डालें',
        'or' => 'या',
        'choose_files' => 'फ़ाइलें चुनें',
        'image_specs' => 'JPG, PNG या WEBP (अधिकतम 5MB)',

        // Section 4: Service Areas
        'sec_service_areas' => '4. सेवा क्षेत्र',
        'select_service_areas' => 'सेवा क्षेत्र चुनें',
        'add_custom_area' => '+ कस्टम क्षेत्र जोड़ें',
        'prompt_custom_area' => 'कस्टम क्षेत्र का नाम दर्ज करें:',

        // Section 5: Additional Information
        'sec_additional' => '5. अतिरिक्त जानकारी',
        'fuel_type' => 'ईंधन का प्रकार',
        'select_fuel' => '-- ईंधन का प्रकार चुनें --',
        'power_hp' => 'पावर (HP)',
        'power_hp_ph' => 'HP में पावर दर्ज करें',
        'working_hours' => 'काम करने के घंटे',
        'working_hours_ph' => 'काम करने के घंटे दर्ज करें',
        'mark_recommended' => 'अनुशंसित उपकरण के रूप में चिह्नित करें',
        'recommended_desc' => 'यह आपके उपकरण को होमपेज पर अनुशंसित के रूप में दिखाएगा।',

        // Buttons
        'reset' => 'रीसेट करें',
        'save_equipment' => 'उपकरण सहेजें'

    ]
];

// Translation helper function
function __($key) {
    global $translations, $current_lang;
    return $translations[$current_lang][$key] ?? $translations['en'][$key] ?? $key;
}
?>