<?php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Check if language parameter is set via GET request
if (isset($_GET['lang'])) {
    $_SESSION['lang'] = $_GET['lang'];
}

// Default language is English
$current_lang = $_SESSION['lang'] ?? 'en';

// Translation Dictionaries
$translations = [
    'en' => [
        // Index / General Keys
        'title' => 'AGRICULTURE EQUIPMENT RENTAL SYSTEM',
        'hero_title' => 'Smart Solutions for Modern Farming',
        'hero_sub' => 'Rent quality agricultural equipment easily and grow your productivity.',
        'login' => 'Login',
        'register' => 'Register',
        'trusted' => 'Trusted & Secure',
        'trusted_desc' => 'Your data is safe with us',
        'quality' => 'Quality Equipment',
        'quality_desc' => 'Well-maintained and reliable',
        'near' => 'Near You',
        'near_desc' => 'Find equipment nearby',
        // Login & Navigation Keys
        'title'             => 'Agriculture Equipment Rental System',
        'home'              => 'Home',
        'how_it_works'      => 'How It Works',
        'welcome_back'      => 'Welcome Back!',
        'login_sub'         => 'Login to your account and start renting the best agricultural equipment near you.',
        'login'             => 'Login',
        'register'          => 'Register',
        'email_or_phone'    => 'Email / Phone Number',
        'enter_email_phone' => 'Enter your email or mobile number',
        'password'          => 'Password',
        'enter_password'    => 'Enter your password',
        'remember_me'       => 'Remember Me',
        'forgot_password'   => 'Forgot Password?',
        'dont_have_account' => "Don't have an account?",
        'register' => 'Register',
        'trusted' => 'Trusted & Secure',
        'trusted_desc' => 'Your information is safely stored with us',
        'quality' => 'Quality Equipment',
        'quality_desc' => 'Well-maintained and top-tier condition',
        'near' => 'Near You',
        'near_desc' => 'Find equipment in your local area',
        'terms_notice' => 'By logging in, you agree to our <a href="#" class="text-success text-decoration-none fw-semibold">Terms & Conditions</a> and <a href="#" class="text-success text-decoration-none fw-semibold">Privacy Policy</a>.',
        'popular_categories' => 'POPULAR CATEGORIES',
        'tractor' => 'Tractor',
        'harvesting' => 'Harvesting',
        'irrigation' => 'Irrigation',
        'tillage' => 'Tillage',
        'seeding' => 'Seeding',
        'spraying' => 'Spraying',
        'all_rights_reserved' => 'All rights reserved.',
        // How it works
        'how_it_works' => 'How It Works',
        'how_it_works_sub' => 'Simple steps to rent or list agricultural equipment in your local area.',
        'for_renters' => 'For Renters (Farmers)',
        'search_equipment' => 'Search Equipment',
        'search_equipment_desc' => 'Find tractors, harvesters, or tillage tools available near your location.',
        'book_and_pay' => 'Book & Pay',
        'book_and_pay_desc' => 'Select your required rental duration and confirm the booking request securely.',
        'start_farming' => 'Start Farming',
        'start_farming_desc' => 'Get the equipment delivered or pick it up directly from the owner to start work.',
        'for_lenders' => 'For Equipment Owners (Lenders)',
        'list_equipment' => 'List Equipment',
        'list_equipment_desc' => 'Post details, pricing, and images of your idle tractors or farming tools.',
        'accept_requests' => 'Accept Requests',
        'accept_requests_desc' => 'Review incoming rental requests from local farmers and accept them easily.',
        'earn_income' => 'Earn Income',
        'earn_income_desc' => 'Receive payment directly once the rental agreement period is completed.',
        'popular_categories' => 'POPULAR CATEGORIES',
        'tractor' => 'Tractor',
        'harvesting' => 'Harvesting',
        'irrigation' => 'Irrigation',
        'tillage' => 'Tillage',
        'seeding' => 'Seeding',
        'spraying' => 'Spraying',
        'all_rights_reserved' => 'All rights reserved.'
        
    ],

    'kn' => [
         // Index / General Keys
        'title' => 'ಕೃಷಿ ಉಪಕರಣ ಬಾಡಿಗೆ ವ್ಯವಸ್ಥೆ',
        'hero_title' => 'ಆಧುನಿಕ ಕೃಷಿಗಾಗಿ ಸ್ಮಾರ್ಟ್ ಪರಿಹಾರಗಳು',
        'hero_sub' => 'ಉತ್ತಮ ಗುಣಮಟ್ಟದ ಕೃಷಿ ಉಪಕರಣಗಳನ್ನು ಸುಲಭವಾಗಿ ಬಾಡಿಗೆಗೆ ಪಡೆಯಿರಿ.',
        'login' => 'ಲಾಗಿನ್',
        'register' => 'ನೋಂದಣಿ',
        'trusted' => 'ವಿಶ್ವಾಸಾರ್ಹ ಮತ್ತು ಸುರಕ್ಷಿತ',
        'trusted_desc' => 'ನಿಮ್ಮ ಡೇಟಾ ನಮ್ಮ ಬಳಿ ಸುರಕ್ಷಿತವಾಗಿದೆ',
        'quality' => 'ಗುಣಮಟ್ಟದ ಉಪಕರಣಗಳು',
        'quality_desc' => 'ಉತ್ತಮ ನಿರ್ವಹಣೆ ಮತ್ತು ನಂಬಿಕಸ್ಥ',
        'near' => 'ನಿಮ್ಮ ಹತ್ತಿರ',
        'near_desc' => 'ಸಮೀಪದ ಉಪಕರಣಗಳನ್ನು ಹುಡುಕಿ',
        // Login & Navigation Keys
        'home'              => 'ಮುಖ್ಯ ಪುಟ',
        'how_it_works'      => 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
        'welcome_back'      => 'ಮತ್ತೆ ಸ್ವಾಗತ!',
        'login_sub'         => 'ನಿಮ್ಮ ಖಾತೆಗೆ ಲಾಗಿನ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಹತ್ತಿರದ ಅತ್ಯುತ್ತಮ ಕೃಷಿ ಉಪಕರಣಗಳನ್ನು ಬಾಡಿಗೆಗೆ ಪಡೆಯಿರಿ.',
        'email_or_phone'    => 'ಇಮೇಲ್ / ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
        'enter_email_phone' => 'ನಿಮ್ಮ ಇಮೇಲ್ ಅಥವಾ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
        'password'          => 'ಪಾಸ್ವರ್ಡ್',
        'enter_password'    => 'ನಿಮ್ಮ ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ',
        'remember_me'       => 'ನನ್ನನ್ನು ನೆನಪಿಡಿ',
        'forgot_password'   => 'ಪಾಸ್ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?',
        'dont_have_account' => 'ಖಾತೆ ಇಲ್ಲವೇ?',
        'register' => 'ನೋಂದಣಿ',
        'trusted' => 'ವಿಶ್ವಾಸಾರ್ಹ ಮತ್ತು ಸುರಕ್ಷಿತ',
        'trusted_desc' => 'ನಿಮ್ಮ ವಿವರಗಳು ನಮ್ಮ ಬಳಿ ಸುರಕ್ಷಿತವಾಗಿವೆ',
        'quality' => 'ಗುಣಮಟ್ಟದ ಉಪಕರಣಗಳು',
        'quality_desc' => 'ಉತ್ತಮ ನಿರ್ವಹಣೆ ಮತ್ತು ಸುಸ್ಥಿತಿ',
        'near' => 'ನಿಮ್ಮ ಹತ್ತಿರ',
        'near_desc' => 'ಸಮೀಪದ ಉಪಕರಣಗಳನ್ನು ಹುಡುಕಿ',
        'terms_notice' => 'ಲಾಗಿನ್ ಮಾಡುವ ಮೂಲಕ, ನೀವು ನಮ್ಮ <a href="#" class="text-success text-decoration-none fw-semibold">ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು</a> ಮತ್ತು <a href="#" class="text-success text-decoration-none fw-semibold">ಗೌಪ್ಯತಾ ನೀತಿ</a>ಗೆ ಒಪ್ಪುತ್ತೀರಿ.',
        'popular_categories' => 'ಜನಪ್ರಿಯ ವರ್ಗಗಳು',
        'tractor' => 'ಟ್ರಾಕ್ಟರ್',
        'harvesting' => 'ಕೊಯ್ಲು',
        'irrigation' => 'ನೀರಾವರಿ',
        'tillage' => 'ಉಳುಮೆ',
        'seeding' => 'ಬಿತ್ತನೆ',
        'spraying' => 'ಸಿಂಪಡಣೆ',
        'all_rights_reserved' => 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
        // how it works
          'how_it_works' => 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
          'how_it_works_sub' => 'ನಿಮ್ಮ ಸ್ಥಳೀಯ ಪ್ರದೇಶದಲ್ಲಿ ಕೃಷಿ ಉಪಕರಣಗಳನ್ನು ಬಾಡಿಗೆಗೆ ಪಡೆಯಲು ಅಥವಾ ನೀಡಲು ಸರಳ ಹಂತಗಳು.',
          'for_renters' => 'ಬಾಡಿಗೆದಾರರಿಗೆ (ರೈತರಿಗೆ)',
          'search_equipment' => 'ಉಪಕರಣಗಳನ್ನು ಹುಡುಕಿ',
          'search_equipment_desc' => 'ನಿಮ್ಮ ಹತ್ತಿರ ಲಭ್ಯವಿರುವ ಟ್ರ್ಯಾಕ್ಟರ್‌ಗಳು, ಕೊಯ್ಲು ಯಂತ್ರಗಳು ಅಥವಾ ಉಳುವಿಕೆ ಉಪಕರಣಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಿ.',
          'book_and_pay' => 'ಬುಕ್ ಮಾಡಿ ಮತ್ತು ಪಾವತಿಸಿ',
          'book_and_pay_desc' => 'ನಿಮಗೆ ಅಗತ್ಯವಿರುವ ಬಾಡಿಗೆಯ ಸಮಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ ಮತ್ತು ಬುಕಿಂಗ್ ಅನ್ನು ದೃಢೀಕರಿಸಿ.',
          'start_farming' => 'ಬೆಳೆ ಕೃಷಿ ಪ್ರಾರಂಭಿಸಿ',
          'start_farming_desc' => 'ಉಪಕರಣಗಳನ್ನು ಮನೆಗೆ ತರಿಸಿಕೊಳ್ಳಿ ಅಥವಾ ಮಾಲೀಕರಿಂದ ನೇರವಾಗಿ ಪಡೆದುಕೊಂಡು ಕೆಲಸ ಪ್ರಾರಂಭಿಸಿ.',
          'for_lenders' => 'ಉಪಕರಣಗಳ ಮಾಲೀಕರಿಗೆ (ನೀಡುವವರಿಗೆ)',
          'list_equipment' => 'ಉಪಕರಣಗಳ ಮಾಹಿತಿ ನೀಡಿ',
          'list_equipment_desc' => 'ನಿಮ್ಮ ಬಳಿ ಸುಮ್ಮನೆ ಇರುವ ಟ್ರ್ಯಾಕ್ಟರ್ ಅಥವಾ ಕೃಷಿ ಉಪಕರಣಗಳ ವಿವರ, ದರ ಮತ್ತು ಚಿತ್ರಗಳನ್ನು ಸೇರಿಸಿ.',
          'accept_requests' => 'ಕೋರಿಕೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ',
          'accept_requests_desc' => 'ಸ್ಥಳೀಯ ರೈತರಿಂದ ಬರುವ ಬಾಡಿಗೆ ಕೋರಿಕೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸುಲಭವಾಗಿ ಸ್ವೀಕರಿಸಿ.',
          'earn_income' => 'ಆದಾಯ ಗಳಿಸಿ',
          'earn_income_desc' => 'ಬಾಡಿಗೆಯ ಸಮಯ ಮುಗಿದ ನಂತರ ನೇರವಾಗಿ ಹಣವನ್ನು ಪಡೆದುಕೊಳ್ಳಿ.',
           'popular_categories' => 'ಜನಪ್ರಿಯ ವರ್ಗಗಳು',
        'tractor' => 'ಟ್ರಾಕ್ಟರ್',
        'harvesting' => 'ಕೊಯ್ಲು',
        'irrigation' => 'ನೀರಾವರಿ',
        'tillage' => 'ಉಳುಮೆ',
        'seeding' => 'ಬಿತ್ತನೆ',
        'spraying' => 'ಸಿಂಪಡಣೆ',
        'all_rights_reserved' => 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.'
    ],
    'hi' => [
        // Index / General Keys
        'title' => 'कृषि उपकरण किराया प्रणाली',
        'hero_title' => 'आधुनिक खेती के लिए स्मार्ट समाधान',
        'hero_sub' => 'गुणवत्तापूर्ण कृषि उपकरण आसानी से किराए पर लें।',
        'login' => 'लॉग इन',
        'register' => 'पंजीकरण',
        'trusted' => 'विश्वसनीय और सुरक्षित',
        'trusted_desc' => 'आपका डेटा हमारे पास सुरक्षित है',
        'quality' => 'गुणवत्ता उपकरण',
        'quality_desc' => 'अच्छी तरह से रखरखाव और विश्वसनीय',
        'near' => 'आपके पास',
        'near_desc' => 'आस-पास के उपकरण खोजें',
        // Login & Navigation Keys
        'home'              => 'होम',
        'how_it_works'      => 'यह कैसे काम करता है',
        'welcome_back'      => 'वेलकम बैक!',
        'login_sub'         => 'अपने खाते में लॉगिन करें और अपने पास के सबसे अच्छे कृषि उपकरणों को किराए पर लें।',
        'email_or_phone'    => 'ईमेल / फ़ोन नंबर',
        'enter_email_phone' => 'अपना ईमेल या मोबाइल नंबर दर्ज करें',
        'password'          => 'पासवर्ड',
        'enter_password'    => 'अपना पासवर्ड दर्ज करें',
        'remember_me'       => 'मुझे याद रखो',
        'forgot_password'   => 'पासवर्ड भूल गए?',
        'dont_have_account' => 'खाता नहीं है?',
        'register' => 'पंजीकरण',
        'trusted' => 'विश्वसनीय और सुरक्षित',
        'trusted_desc' => 'आपकी जानकारी हमारे पास सुरक्षित रूप से संग्रहीत है',
        'quality' => 'गुणवत्ता उपकरण',
        'quality_desc' => 'अच्छी तरह से रखरखाव और शीर्ष-स्तरीय स्थिति',
        'near' => 'आपके पास',
        'near_desc' => 'अपने स्थानीय क्षेत्र में उपकरण खोजें',
        'terms_notice' => 'लॉगिन करके, आप हमारी <a href="#" class="text-success text-decoration-none fw-semibold">नियम और शर्तें</a> और <a href="#" class="text-success text-decoration-none fw-semibold">गोपनीयता नीति</a> से सहमत होते हैं।',
        'popular_categories' => 'लोकप्रिय श्रेणियाँ',
        'tractor' => 'ट्रैक्टर',
        'harvesting' => 'फसल काटना',
        'irrigation' => 'सिंचाई',
        'tillage' => 'जुताई',
        'seeding' => 'बुवाई',
        'spraying' => 'छिड़काव',
        'all_rights_reserved' => 'सर्वाधिकार सुरक्षित।',
        // how it works
        'how_it_works' => 'यह कैसे काम करता है',
        'how_it_works_sub' => 'अपने स्थानीय क्षेत्र में कृषि उपकरण किराए पर लेने या देने के आसान चरण।',
        'for_renters' => 'किराएदारों के लिए (किसान)',
        'search_equipment' => 'उपकरण खोजें',
        'search_equipment_desc' => 'अपने पास उपलब्ध ट्रैक्टर, हार्वेस्टर या जुताई के उपकरण खोजें।',
        'book_and_pay' => 'बुक करें और भुगतान करें',
        'book_and_pay_desc' => 'अपनी आवश्यकता अनुसार समय चुनें और सुरक्षित रूप से बुकिंग की पुष्टि करें।',
        'start_farming' => 'खेती शुरू करें',
        'start_farming_desc' => 'उपकरण की डिलीवरी पाएं या सीधे मालिक से प्राप्त करके काम शुरू करें।',
        'for_lenders' => 'उपकरण मालिकों के लिए (किराए पर देने वाले)',
       'list_equipment' => 'उपकरण जोड़ें',
       'list_equipment_desc' => 'अपने खाली पड़े ट्रैक्टर या कृषि उपकरणों का विवरण, किराया और तस्वीरें अपलोड करें।',
       'accept_requests' => 'अनुरोध स्वीकार करें',
       'accept_requests_desc' => 'स्थानीय किसानों से मिलने वाले किराए के अनुरोधों की समीक्षा करें और स्वीकार करें।',
       'earn_income' => 'कमाई करें',
       'earn_income_desc' => 'किराए की अवधि पूरी होने पर सीधे भुगतान प्राप्त करें।',
        'popular_categories' => 'लोकप्रिय श्रेणियाँ',
        'tractor' => 'ट्रैक्टर',
        'harvesting' => 'फसल काटना',
        'irrigation' => 'सिंचाई',
        'tillage' => 'जुताई',
        'seeding' => 'बुवाई',
        'spraying' => 'छिड़काव',
        'all_rights_reserved' => 'सर्वाधिकार सुरक्षित।'
    ]
];

// Translation helper function
function __($key) {
    global $translations, $current_lang;
    return $translations[$current_lang][$key] ?? $translations['en'][$key] ?? $key;
}
?>